### PR TITLE
ci: Added flake8 style guide enforcement to Poetry package dev dependencies.

### PR DESCRIPTION
**Pull request by michealroberts**
ci: Added flake8 style guide enforcement to Poetry package dev dependencies. 

Includes applying all flake8 styleguide PEP enforcements to base code files.

Includes adding base .flake8 file for exclusions.

### CODE REVIEW

**Comment by michealroberts** [comment]
Dependent #6

**Comment by lgrcia** [comment]
Great, thanks @michealroberts ! I intend to use [black](https://black.readthedocs.io) in this project. If you agree can we make sure to avoid compatibility issues? (I guess it's just about adding [`extend-ignore = E203` ](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8), right?)

**Comment by michealroberts** [comment]
Hey @lgrcia Yeh black is cool, shall we add it in to this MR? Or would you prefer a separate one?

**Comment by lgrcia** [comment]
I just starting formatting on save using black on VSCode. So I am happy to use that if that's the question

**Comment by michealroberts** [comment]
@lgrcia Awesome, same ... we both use viscose so it might be worth adding some settings here :)

Also, I completely forgot to say ... but would you like to experimental try ruff for linting? https://github.com/charliermarsh/ruff

**Comment by lgrcia** [comment]
It seems compatible with black, so happy to try ruff!

**Comment by michealroberts** [comment]
@lgrcia Awesome I will close this MR and implement black + ruff.

**Pull request closed without merging**
